name: "ElementsHighlight"

exports: "ElementsHighlight.js"

author: "subhaze"

category: "Effects"

tags: "[navigation, tween, element, effects]"

demo: "http://mootools.net/shell/2jhSv/155/"

current: "v1.3"

sources:
  - "Source/Elements.Highlight.js"